名称：CI

在：
  推：
    分支：[ stable/v3 ]
  pull_request：
    分支：[ stable/v3 ]

招聘职位：
  releaseJar：
    运行：ubuntu-latest
    步骤：
      - 用途：动作/checkout@v2
      - 用途：actions/setup-java@v1
        与：
          java版本：8

      - 名称：缓存 .gradle/caches
        用途：操作/cache@v1
        与：
          路径：~/.gradle/caches
          键：${{ runner.os }}-gradle-${{ hashFiles（'**/*.gradle*'） }}
          恢复键：${{ runner.os }}-gradle-

      - name：缓存 .gradle/wrapper
        用途：操作/cache@v1
        与：
          路径：~/.gradle/wrapper
          键：${{ runner.os }}-gradle-wrapper-${{ hashFiles（'**/*.gradle'） }}
          恢复键：${{ runner.os }}-gradle-wrapper-

      - name：授予 gradlew 的执行权限
        运行：chmod +x gradlew

# - name： 使用 Gradle 构建
# 运行： ./gradlew clean build -s

      # 第一次构建
      - 名称：Build
        编号： build_1
        运行：./gradlew build
      # 第二次构建
      - 名称：生成（重试 1）
        编号： build_2
        if： steps.build_1.outcome == 'failure'
        运行：./gradlew build
       # 第三次构建
      - 名称：生成（重试 2）
        编号： build_3
        if： steps.build_2.outcome == 'failure'
        运行：./gradlew build
       # 第四次构建
      - 名称：生成（重试 3）
        编号： build_4
        if： steps.build_3.outcome == 'failure'
        运行：./gradlew build

      - name： 上传工件
        用途：actions/upload-artifact@v2
        与：
          名称：TrMenu Artifact
          路径：build/libs/*.jar
